name: Download YouTube Video

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'YouTube URL'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3

      - name: Setup YouTube cookies
        uses: AnimMouse/setup-yt-dlp/cookies@v3
        with:
          cookies: ${{ secrets.YOUTUBE_COOKIES }}

      - name: Download Video
        run: |
          yt-dlp -o "video.%(ext)s" "${{ github.event.inputs.url }}"

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          filename: "video.*"
          folderId: ${{ secrets.DRIVE_FOLDER_ID }}
